//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> IPUser { get; set; }
        public string CommentContent { get; set; }
        public Nullable<int> CountLike { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
