//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int InfoID { get; set; }
        public string Title { get; set; }
        public string InfoContent { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKey { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
