//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        public int SupportID { get; set; }
        public string Name { get; set; }
        public string Yahoo { get; set; }
        public string Gmail { get; set; }
        public string Skype { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string SupportContent { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
