//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int TransactionID { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> IDUser { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserPhone { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Payment { get; set; }
        public string PaymentInfo { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual User User { get; set; }
    }
}
