//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VideoID { get; set; }
        public string Name { get; set; }
        public string Images { get; set; }
        public string Intro { get; set; }
        public string Link { get; set; }
        public Nullable<int> CountView { get; set; }
        public Nullable<int> Feature { get; set; }
        public Nullable<int> VideoView { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
